In [2]:
import pandas as pd

In [57]:
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv("/Users/andrewdrabkin/Documents/BLMA/new_all_data_BMLA.csv")

In [13]:
df.shape

(112907, 126)

In [16]:
df['zcta'].nunique()

19713

In [17]:
years_per_zip = df.groupby('zcta')['date'].nunique()

years_per_zip.value_counts().sort_index()

date
1       46
2      989
3       95
4      163
5      574
6    17846
Name: count, dtype: int64

In [58]:
df.head(50)

,zcta,date_census,household_income,household_income_prior,household_income_delta,pct_below_pov_line,pct_below_pov_line_prior,pct_below_pov_line_delta,total_pop,total_pop_delta,total_pop_prior,pct_wfh,pct_wfh_delta,pct_wfh_prior,pct_0_bed_rentals,pct_1_bed_rentals,pct_2_bed_rentals,pct_3_bed_rentals,pct_4_bed_rentals,pct_5_bed_rentals,pct_0_bed_stock,pct_1_bed_stock,pct_2_bed_stock,pct_3_bed_stock,pct_4_bed_stock,pct_5_bed_stock,pct_foreign,pct_foreign_delta,pct_foreign_prior,pct_white,pct_white_delta,pct_white_prior,pct_black,pct_black_delta,pct_black_prior,pct_asian,pct_asian_delta,pct_asian_prior,pct_hispanic,pct_hispanic_delta,pct_hispanic_prior,total_housing_units,total_housing_units_delta,total_housing_units_prior,pct_with_bachelor,pct_with_bachelor_prior,pct_with_bachelor_delta,pct_under_18,pct_under_18_prior,pct_under_18_delta,pct_under_5,pct_under_5_prior,pct_under_5_delta,renter_occupied_homes,m_pct_25_29,m_pct_30_34,f_pct_25_29,f_pct_30_34,average_home_age,pct_over_65,pct_over_65_prior,pct_over_65_delta,pct_vacancy,pct_vacancy_prior,pct_vacancy_delta,pct_owner_occupied,pct_mortgage,pct_sfh,total_rental_homes,month,year,date_zillow,value_1_bed,value_2_bed,value_3_bed,value_4_bed,value_5_bed,all_homes,all_homes_projections,all_homes_prior,all_homes_yy_smoothed,all_homes_200701,all_homes_201201,dollar_drop_2007_2012,date,median_listing_price,active_listing_count,median_days_on_market,total_listing_count,new_listing_count,price_drops_pct_of_inventory,price_reduced_count,average_listing_price,median_listing_price_per_square_foot,active_listing_count_historical,total_listing_count_yy_smoothed,median_days_on_market_yy_smoothed,median_listing_price_yy_smoothed,average_listing_price_yy_smoothed,Unnamed: 0,X,total_loan_applications,total_loan_origination,total_loans_denials,total_gov_loans_originated,total_conv_loans_originated,total_first_loans_originated,total_second_loans_originated,total_cash_out_refinances,total_investment_property_mortgages,total_second_property_mortgages,pct_loan_denials,pct_gov_loans,pct_conv_loans,pct_first_lien,pct_second_lien,debt_to_income,loan_to_value,pct_high_ltv,pct_very_high_ltv,avg_first_lien_ir,pct_cash_out_refinance,pct_investor_loans,pct_second_loans,avg_loan_amt,date_HMDA
0,1001,2018-01-01,62100.0,58700.0,0.058,0.090,0.092,-0.022,17600,0.022,17200.0,0.028,0.647,0.017,0.105,0.311,0.434,0.092,0.028,0.031,0.027,0.112,0.389,0.314,0.127,0.032,0.084,-0.229,0.109,0.883,-0.012,0.894,0.020,0.667,0.012,0.031,0.148,0.027,0.055,0.038,0.053,7770,0.050,7400.0,0.325,0.253,0.285,0.187,0.203,-0.079,0.045,0.057,-0.211,2000,0.507,0.373,0.493,0.627,1967.0,0.241,0.186,0.296,0.037,0.046,-0.196,0.733,0.648,0.556,2000.0,1,2018,2018-01-01,76000.0,167000.0,232000.0,258000.0,291000.0,210000.0,NaN,203000.0,0.0336,213000.0,185000.0,-0.1310,2018-01-01,222000.0,44.0,65.0,48.0,14.0,0.27,12.0,257000.0,168.0,24.0,-0.10,-0.31,0.10,0.05,2,2,744,470,149,64,406,385,85,61,14,0,0.20,0.14,0.86,0.82,0.18,0.37,0.69,0.39,0.24,4.59,0.13,0.03,0.00,173000.0,2018-01-01
1,1001,2019-01-01,63900.0,60800.0,0.052,0.085,0.084,0.012,17300,0.010,17100.0,0.051,1.833,0.018,0.138,0.276,0.397,0.125,0.029,0.035,0.036,0.103,0.397,0.313,0.116,0.035,0.098,0.021,0.096,0.885,0.000,0.885,0.026,1.364,0.011,0.028,-0.034,0.029,0.052,-0.119,0.059,7620,0.034,7370.0,0.323,0.276,0.170,0.183,0.190,-0.037,0.055,0.059,-0.068,2000,0.543,0.384,0.457,0.616,1968.0,0.235,0.194,0.211,0.028,0.050,-0.440,0.730,0.619,0.551,2000.0,1,2019,2019-01-01,80000.0,173000.0,239000.0,266000.0,301000.0,217000.0,NaN,210000.0,0.0367,213000.0,185000.0,-0.1310,2019-01-01,206000.0,50.0,68.0,57.0,14.0,0.28,14.0,250000.0,148.0,24.0,0.28,0.23,-0.08,-0.01,19402,2,881,577,172,77,500,489,88,67,14,4,0.20,0.13,0.87,0.85,0.15,0.37,0.69,0.37,0.27,4.14,0.12,0.02,0.01,185000.0,2019-01-01
2,1001,2020-01-01,66100.0,60200.0,0.099,0.084,0.074,0.135,16100,-0.079,17400.0,0.068,2.091,0.022,0.168,0.188,0.435,0.133,0.033,0.044,0.043,0.063,0.403,0.332,0.134,0.025,0.079,-0.210,0.100,0.869,-0.010,0.878,0.028,1.154,0.013,0.032,-0.135,0.037,0.055,-0.141,0.064,7090,-0.048,7450.0,0.348,0.280,0.243,0.177,0.191,-0.073,0.056,0.052,0.077,1820,0.565,0.430,0.435,0.570,1967.0,0.233,0.197,0.183,0.031,0.047,-0.340,0.735,0.594,0.560,1820.0,1,2020,2020-01-01,84000.0,182000.0,250000.0,277000.0,313000.0,228000.0,NaN,217000.0,0.0431,213000.0,185000.0,-0.1310,2020-01-01,252000.0,29.0,58.0,33.0,22.0,0.28,8.0,297000.0,163.0,24.0,-0.43,-0.09,0.24,0.17,38796,2,1068,751,124,141,610,689,62,123,12,3,0.12,0.19,0.81,0.92,0.08,0.35,0.72,0.35,0.23,3.17,0.16,0.02,0.00,199000.0,2020-01-01
3,1001,2021-01-01,72400.0,56700.0,0.277,0.076,0.088,-0.136,16100,-0.077,17400.0,0.095,3.318,0.022,0.149,0.187,0.444,0.164,0.029,0.027,0.039,0.065,0.373,0.368,0.132,0.023,0.098,0.010,0.097,0.870,0.006,0.865,0.037,1.467,0.015,0.037,-0.075,0.040,0.043,-0.427,0.075,7070,-0.055,7480.0,0.367,0.277,0.325,0.174,0.186,-0.065,0.060,0.047,0.277,1860,0.598,0.526,0.402,0.474,1968.0,0.225,0.215,0.047,0.039,0.039,0.000,0.727,0.612,0.570,1860.0,1,2021,2021-01-01,94000.0,197000.0,274000.0,304000.0,343000.0,249000.0,NaN,228000.0,0.0862,213000.0,185000.0,-0.1310,2021-01-01,249000.0,15.0,25.0,22.0,16.0,0.00,0.0,338000.0,178.0,24.0,-0.19,-0.48,0.00,0.08,58212,2,1214,892,147,138,754,835,57,189,14,5,0.12,0.15,0.85,0.94,0.06,0.34,0.70,0.32,0.19,2.96,0.21,0.02,0.01,207000.0,2021-01-01
4,1001,2022-01-01,73400.0,57700.0,0.272,0.071,0.093,-0.237,16000,-0.085,17500.0,0.097,2.464,0.028,0.127,0.230,0.417,0.179,0.021,0.027,0.033,0.086,0.356,0.389,0.112,0.024,0.097,0.169,0.083,0.853,-0.028,0.878,0.033,1.750,0.012,0.030,-0.032,0.031,0.074,0.121,0.066,6910,-0.105,7720.0,0.354,0.301,0.176,0.177,0.184,-0.038,0.055,0.048,0.146,1800,0.679,0.534,0.321,0.466,1970.0,0.243,0.232,0.047,0.043,0.034,0.265,0.728,0.582,0.556,1800.0,1,2022,2022-01-01,112000.0,221000.0,298000.0,333000.0,383000.0,272000.0,NaN,249000.0,0.0984,213000.0,185000.0,-0.1310,2022-01-01,232000.0,10.0,44.0,14.0,4.0,0.00,0.0,271000.0,172.0,24.0,-0.38,-0.13,0.09,-0.05,77626,2,798,544,129,59,485,416,128,105,3,2,0.16,0.11,0.89,0.76,0.24,0.37,0.60,0.33,0.20,4.52,0.19,0.01,0.00,226000.0,2022-01-01
5,1001,2023-01-01,71900.0,62100.0,0.157,0.072,0.090,-0.200,16100,-0.084,17600.0,0.116,3.143,0.028,0.112,0.282,0.443,0.147,0.011,0.004,0.030,0.102,0.339,0.395,0.114,0.020,0.108,0.286,0.084,0.830,-0.060,0.883,0.037,0.850,0.020,0.038,0.226,0.031,0.078,0.418,0.055,7030,-0.095,7770.0,0.356,0.325,0.095,0.174,0.187,-0.070,0.053,0.045,0.178,1850,0.639,0.534,0.361,0.466,1970.0,0.233,0.241,-0.033,0.031,0.037,-0.162,0.729,0.552,0.543,1850.0,1,2023,2023-01-01,123000.0,243000.0,320000.0,355000.0,407000.0,296000.0,NaN,272000.0,0.0929,213000.0,185000.0,-0.1310,2023-01-01,357000.0,21.0,31.0,25.0,18.0,0.38,8.0,398000.0,209.0,24.0,0.39,0.69,0.40,0.39,98094,2,576,380,105,41,339,273,107,32,6,2,0.18,0.11,0.89,0.72,0.28,0.39,0.59,0.36,0.21,6.51,0.08,0.02,0.01,248000.0,2023-01-01
6,1002,2018-01-01,55900.0,54400.0,0.026,0.287,0.313,-0.083,30100,0.027,29300.0,0.091,-0.099,0.101,0.040,0.200,0.420,0.216,0.103,0.021,0.029,0.126,0.292,0.304,0.198,0.050,0.173,0.068,0.162,0.713,-0.039,0.742,0.062,0.378,0.045,0.110,0.019,0.108,0.073,-0.039,0.076,10900,0.086,10100.0,0.670,0.672,-0.003,0.124,0.132,-0.061,0.031,0.030,0.033,5300,0.507,0.544,0.493,0.456,1973.0,0.119,0.097,0.227,0.098,0.082,0.195,0.464,0.582,0.442,5300.0,1,2018,2018-01-01,139000.0,199000.0,306000.0,389000.0,472000.0,328000.0,NaN,320000.0,0.0229,320000.0,291000.0,-0.0906,2018-01-01,367000.0,65.0,102.0,69.0,22.0,0.09,6.0,476000.0,206.0,31.0,-0.02,-0.29,0.09,0.23,3,3,475,311,75,6,305,281,30,47,25,7,0.16,0.02,0.98,0.90,0.10,0.36,0.67,0.22,0.08,4.29,0.15,0.08,0.02,265000.0,2018-01-01
7,1002,2019-01-01,61200.0,55100.0,0.110,0.260,0.319,-0.185,30000,0.006,29800.0,0.079,-0.347,0.121,0.036,0.215,0.376,0.222,0.131,0.021,0.029,0.139,0.267,0.302,0.216,0.047,0.183,0.089,0.168,0.709,-0.035,0.735,0.056,0.191,0.047,0.112,-0.034,0.116,0.075,0.000,0.075,11000,0.065,10300.0,0.664,0.698,-0.049,0.126,0.127,-0.008,0.029,0.030,-0.033,5000,0.537,0.565,0.463,0.435,1973.0,0.134,0.098,0.367,0.106,0.078,0.359,0.490,0.538,0.456,5000.0,1,2019,2019-01-01,143000.0,207000.0,320000.0,406000.0,495000.0,344000.0,NaN,328000.0,0.0501,320000.0,291000.0,-0.0906,2019-01-01,490000.0,46.0,101.0,50.0,10.0,0.17,8.0,523000.0,205.0,31.0,-0.19,0.13,0.22,0.06,19403,3,418,296,58,12,284,267,29,34,21,10,0.14,0.04,0.96,0.90,0.10,0.33,0.69,0.28,0.11,3.95,0.11,0.07,0.03,308000.0,2019-01-01
8,1002,2020-01-01,60500.0,50500.0,0.198,0.238,0.329,-0.277,30100,0.011,29800.0,0.106,0.010,0.105,0.123,0.201,0.313,0.232,0.113,0.019,0.065,0.126,0.223,0.310,0.222,0.054,0.177,0.047,0.169,0.701,-0.042,0.732,0.058,0.234,0.047,0.104,-0.194,0.129,0.075,0.172,0.064,11200,0.073,10500.0,0.711,0.680,0.046,0.127,0.121,0.050,0.036,0.032,0.125,5130,0.542,0.580,0.458,0.420,1973.0,0.123,0.107,0.150,0.094,0.090,0.044,0.496,0.541,0.462,5130.0,1,2020,2020-01-01,NaN,215000.0,328000.0,412000.0,499000.0,351000.0,NaN,344000.0,0.0167,320000.0,291000.0,-0.0906,2020-01-01,456000.0,42.0,135.0,46.0,14.0,0.05,2.0,500000.0,204.0,31.0,-0.18,0.10,-0.01,0.01,38797,3,639,421,75,18,403,404,17,54,22,11,0.12,0.04,0.96,0.96,0.04,0.32,0.69,0.20,0.09,3.06,0.13,0.05,0.03,311000.0,2020-01-01
9,1002,2021-01-01,65000.0,48900.0,0.329,0.230,0.337,-0.318,27300,-0.088,30000.0,0.155,0.890,0.082,0.124,0.211,0.284,0.235,0.109,0.038,0.068,0.136,0.219,0.309,0.201,0.066,0.171,0.036,0.165,0.706,-0.042,0.737,0.060,0.053,0.057,0.096,-0.179,0.117,0.075,0.210,0.062,11300,0.076,10500.0,0.714,0.658,0.085,0.132,0.123,0.073,0.034,0.028,0.214,5220,0.524,0.574,0.476,0.426,1973.0,0.130,0.108,0.204,0.116,0.089,0.303,0.477,0.549,0.452,5220.0,1,2021,2021-01-01,163000.0,232000.0,359000.0,452000.0,548000.0,384000.0,NaN,351000.0,0.0866,320000.0,291000.0,-0.0906,2021-01-01,549000.0,17.0,55.0,20.0,8.0,0.24,4.0,528000.0,224.0,31.0,-0.34,-0.47,0.19,0.08,58213,3,628,452,67,17,435,435,17,89,22,15,0.11,0.04,0.96,0.96,0.04,0.31,0.65,0.20,0.06,2.84,0.20,0.05,0.03,301000.0,2021-01-01
10,1002,2022-01-01,74300.0,52400.0,0.418,0.222,0.313,-0.291,23000,-0.241,30300.0,0.172,1.048,0.084,0.133,0.234,0.277,0.206,0.114,0.036,0.067,0.163,0.211,0.280,0.202,0.077,0.159,-0.042,0.166,0.709,-0.034,0.734,0.041,-0.268,0.056,0.091,-0.216,0.116,0.083,0.317,0.063,10200,-0.065,10900.0,0.725,0.670,0.082,0.132,0.127,0.039,0.030,0.030,0.000,4520,0.509,0.638,0.491,0.362,1974.0,0.152,0.111,0.369,0.141,0.087,0.621,0.485,0.551,0.456,4520.0,1,2022,2022-01-01,183000.0,255000.0,390000.0,499000.0,608000.0,419000.0,NaN,384000.0,0.0979,320000.0,291000.0,-0.0906,2022-01-01,535000.0,9.0,76.0,12.0,8.0,0.00,0.0,547000.0,201.0,31.0,-0.52,0.09,-0.01,0.02,77627,3,440,303,54,3,300,245,58,36,15,10,0.12,0.01,0.99,0.81,0.19,0.34,0.58,0.21,0.06,4.01,0.12,0.05,0.03,511000.0,2022-01-01
11,1002,2023-01-01,69400.0,55900.0,0.243,0.230,0.287,-0.199,24700,-0.178,30100.0,0.206,1.264,0.091,0.131,0.228,0.291,0.207,0.112,0.031,0.066,0.158,0.211,0.289,0.204,0.072,0.153,-0.116,0.173,0.706,-0.010,0.713,0.047,-0.242,0.062,0.086,-0.218,0.110,0.094,0.288,0.073,11100,0.013,10900.0,0.739,0.670,0.103,0.131,0.124,0.056,0.031,0.031,0.000,4990,0.580,0.578,0.420,0.422,1974.0,0.160,0.119,0.345,0.124,0.098,0.265,0.487,0.540,0.457,4990.0,1,2023,2023-01-01,213000.0,284000.0,428000.0,546000.0,665000.0,459000.0,NaN,419000.0,0.0976,320000.0,291000.0,-0.0906,2023-01-01,535000.0,13.0,42.0,17.0,10.0,0.31,4.0,555000.0,250.0,31.0,0.00,-0.48,0.04,0.05,98095,3,298,199,41,7,192,135,64,7,11,2,0.14,0.04,0.96,0.68,0.32,0.35,0.48,0.18,0.06,5.93,0.04,0.06,0.01,339000.0,2023-01-01
12,1005,2018-01-01,68300.0,68600.0,-0.005,0.069,0.047,0.468,4990,-0.068,5360.0,0.162,0.339,0.121,0.000,0.634,0.312,0.000,0.055,0.000,0.000,0.125,0.230,0.445,0.131,0.069,0.029,0.208,0.024,0.945,-0.018,0.962,0.023,6.667,0.003,0.008,-0.579,0.019,0.012,-0.200,0.015,2070,-0.072,2240.0,0.324,0.235,0.379,0.206,0.258,-0.202,0.029,0.045,-0.356,292,0.619,0.625,0.381,0.375,1968.0,0.154,0.140,0.100,0.133,0.133,0.000,0.838,0.754,0.797,292.0,1,2018,2018-01-01,NaN,191000.0,229000.0,264000.0,278000.0,226000.0,NaN,212000.0,0.0668,234000.0,173000.0,-0.2610,2018-01-01,254000.0,16.0,86.0,19.0,6.0,0.25,4.0,249000.0,124.0,13.0,-0.07,-0.16,0.08,0.06,5,5,188,115,46,31,84,87,28,15,2,3,0.24,0.27,0.73,0.76,0.24,0.39,0.75,0.48,0.39,4.68,0.13,0.02,0.03,194000.0,2018-01-01
13,1005,2019-01-01,67300.0,68400.0,-0.015,0.086,0.044,0.955,5130,0.003,5110.0,0.150,0.154,0.130,0.000,0.781,0.111,0.000,0.107,0.000,0.000,0.145,0.201,0.431,0.154,0.069,0.036,0.636,0.022,0.938,-0.027,0.964,0.024,7.000,0.003,0.006,-0.684,0.019,0.020,0.429,0.014,2160,-0.011,2180.0,0.328,0.211,0.555,0.196,0.262,-0.252,0.025,0.039,-0.359,270,0.612,0.497,0.388,0.503,1973.0,0.155,0.144,0.076,0.098,0.158,-0.380,0.861,0.697,0.776,270.0,1,2019,2019-01-01,NaN,205000.0,243000.0,278000.0,292000.0,240000.0,NaN,226000.0,0.0693,234000.0,173000.0,-0.2610,2019-01-01,242000.0,20.0,111.0,24.0,6.0,0.10,2.0,369000.0,143.0,13.0,0.38,0.18,-0.02,0.40,19405,5,232,163,38,54,109,141,22,34,5,1,0.16,0.33,0.67,0.87,0.13,0.38,0.78,0.48,0.39,4.29,0.21,0.03,0.01,216000.0,2019-01-01
14,1005,2020-01-01,80100.0,68800.0,0.164,0.111,0.053,1.094,5170,-0.007,5200.0,0.128,0.008,0.127,0.000,0.457,0.000,0.221,0.321,0.000,0.000,0.093,0.149,0.550,0.161,0.047,0.032,0.882,0.017,0.936,-0.028,0.963,0.020,1.500,0.008,0.003,-0.812,0.016,0.035,1.917,0.012,2050,-0.054,2160.0,0.378,0.240,0.575,0.180,0.242,-0.256,0.016,0.032,-0.500,140,0.783,0.484,0.217,0.516,1973.0,0.148,0.153,-0.033,0.081,0.163,-0.503,0.926,0.749,0.796,140.0,1,2020,2020-01-01,NaN,215000.0,253000.0,288000.0,297000.0,251000.0,NaN,240000.0,0.0371,234000.0,173000.0,-0.2610,2020-01-01,287000.0,12.0,59.0,13.0,4.0,0.00,0.0,299000.0,185.0,13.0,-0.38,-0.30,0.05,-0.16,38799,5,302,213,48,49,164,205,8,38,3,0,0.16,0.23,0.77,0.96,0.04,0.36,0.79,0.41,0.28,3.32,0.18,0.01,0.00,219000.0,2020-01-01
15,1005,2021-01-01,103000.0,70600.0,0.466,0.118,0.045,1.622,4950,-0.054,5230.0,0.075,-0.645,0.211,0.000,0.000,0.300,0.000,0.700,0.000,0.000,0.051,0.166,0.554,0.175,0.053,0.027,0.688,0.016,0.954,-0.004,0.958,0.004,-0.800,0.020,0.000,-1.000,0.006,0.035,1.333,0.015,1980,-0.094,2190.0,0.377,0.280,0.346,0.178,0.219,-0.187,0.027,0.023,0.174,50,0.729,0.508,0.271,0.492,1973.0,0.134,0.150,-0.107,0.112,0.159,-0.296,0.972,0.748,0.870,50.0,1,2021,2021-01-01,NaN,242000.0,284000.0,327000.0,340000.0,283000.0,NaN,251000.0,0.1140,234000.0,173000.0,-0.2610,2021-01-01,375000.0,8.0,96.0,9.0,0.0,0.00,0.0,406000.0,196.0,13.0,-0.09,0.23,0.43,0.44,58215,5,303,245,28,51,194,237,8,62,3,2,0.09,0.21,0.79,0.97,0.03,0.36,0.71,0.31,0.22,3.05,0.25,0.01,0.01,229000.0,2021-01-01
16,1005,2022-01-01,97400.0,70300.0,0.385,0.089,0.063,0.413,4840,-0.035,5010.0,0.091,-0.468,0.171,0.000,0.000,0.184,0.265,0.551,0.000,0.000,0.021,0.218,0.535,0.172,0.054,0.025,0.250,0.020,0.933,-0.014,0.946,0.011,-0.500,0.022,0.000,-1.000,0.008,0.052,2.059,0.017,1880,-0.100,2090.0,0.345,0.309,0.117,0.159,0.217,-0.267,0.025,0.027,-0.074,98,0.722,0.542,0.278,0.458,1965.0,0.157,0.147,0.068,0.107,0.147,-0.272,0.942,0.686,0.830,98.0,1,2022,2022-01-01,NaN,256000.0,316000.0,362000.0,390000.0,314000.0,NaN,283000.0,0.1200,234000.0,173000.0,-0.2610,2022-01-01,590000.0,5.0,80.0,5.0,0.0,0.00,0.0,712000.0,192.0,13.0,-0.40,-0.22,0.27,0.38,77629,5,251,170,48,29,141,119,51,48,6,0,0.19,0.17,0.83,0.70,0.30,0.38,0.62,0.28,0.22,4.63,0.28,0.04,0.00,285000.0,2022-01-01
17,1005,2023-01-01,97400.0,68300.0,0.426,0.125,0.069,0.812,4790,-0.041,4990.0,0.080,-0.506,0.162,0.000,0.408,0.252,0.118,0.221,0.000,0.000,0.094,0.252,0.410,0.182,0.061,0.027,-0.069,0.029,0.913,-0.034,0.945,0.015,-0.348,0.023,0.000,-1.000,0.008,0.062,4.167,0.012,1880,-0.095,2070.0,0.355,0.324,0.096,0.170,0.206,-0.175,0.025,0.029,-0.138,321,0.637,0.605,0.363,0.395,1962.0,0.161,0.154,0.045,0.100,0.133,-0.248,0.810,0.592,0.770,321.0,1,2023,2023-01-01,NaN,285000.0,347000.0,398000.0,411000.0,344000.0,NaN,314000.0,0.1070,234000.0,173000.0,-0.2610,2023-01-01,152000.0,3.0,52.0,4.0,2.0,0.00,0.0,174000.0,162.0,13.0,-0.60,-0.32,-0.36,-0.44,98096,4,196,124,41,26,98,86,38,22,4,2,0.21,0.21,0.79,0.69,0.31,0.39,0.59,0.31,0.21,6.61,0.18,0.03,0.02,276000.0,2023-01-01
18,1007,2018-01-01,93300.0,71900.0,0.298,0.053,0.084,-0.369,15000,0.020,14700.0,0.043,-0.122,0.049,0.128,0.102,0.481,0.289,0.000,0.000,0.035,0.022,0.209,0.534,0.184,0.016,0.052,0.020,0.051,0.933,0.024,0.911,0.006,-0.667,0.018,0.033,0.435,0.023,0.014,-0.533,0.030,5920,0.006,5890.0,0.478,0.387,0.235,0.224,0.241,-0.071,0.048,0.054,-0.111,986,0.268,0.544,0.732,0.456,1984.0,0.148,0.116,0.276,0.076,0.016,3.750,0.820,0.700,0.782,986.0,1,2018,2018-01-01,NaN,212000.0,284000.0,336000.0,352000.0,282000.0,NaN,273000.0,0.0304,288000.0,248000.0,-0.1390,2018-01-01,376000.0,55.0,113.0,57.0,22.0,0.11,6.0,366000.0,184.0,26.0,-0.13,0.31,0.18,0.16,6,6,620,418,111,49,369,353,65,76,8,3,0.18,0.12,0.88,0.84,0.16,0.36,0.67,0.33,0.21,4.39,0.18,0.02,0.01,223000.0,2018-01-01
19,1007,2019-01-01,91200.0,74200.0,0.229,0.061,0.078,-0.218,15000,0.016,14800.0,0.039,-0.250,0.052,0.152,0.115,0.423,0.309,0.000,0.000,0.041,0.023,0.220,0.517,0.187,0.011,0.061,0.605,0.038,0.919,-0.006,0.925,0.006,-0.455,0.011,0.044,1.444,0.018,0.014,-0.462,0.026,5990,0.017,5890.0,0.486,0.388,0.253,0.227,0.246,-0.077,0.059,0.056,0.054,1030,0.371,0.511,0.629,0.489,1983.0,0.148,0.120,0.233,0.071,0.027,1.630,0.814,0.710,0.773,1030.0,1,2019,2019-01-01,NaN,221000.0,295000.0,348000.0,364000.0,292000.0,NaN,282000.0,0.0413,288000.0,248000.0,-0.1390,2019-01-01,315000.0,42.0,72.0,45.0,28.0,0.19,8.0,326000.0,157.0,26.0,-0.26,-0.25,-0.07,-0.03,19406,6,653,464,102,57,407,388,76,68,7,5,0.16,0.12,0.88,0.84,0.16,0.36,0.68,0.29,0.16,4.09,0.15,0.02,0.01,244000.0,2019-01-01
20,1007,2020-01-01,94800.0,76900.0,0.233,0.050,0.092,-0.457,15100,0.016,14800.0,0.047,-0.203,0.059,0.164,0.260,0.343,0.233,0.000,0.000,0.039,0.050,0.215,0.475,0.198,0.023,0.057,0.462,0.039,0.903,-0.029,0.930,0.007,0.000,0.007,0.035,0.591,0.022,0.026,0.238,0.021,5970,0.006,5930.0,0.466,0.420,0.110,0.212,0.244,-0.131,0.054,0.055,-0.018,982,0.436,0.474,0.564,0.526,1984.0,0.161,0.129,0.248,0.050,0.036,0.389,0.827,0.719,0.779,982.0,1,2020,2020-01-01,NaN,234000.0,306000.0,359000.0,372000.0,304000.0,NaN,292000.0,0.0342,288000.0,248000.0,-0.1390,2020-01-01,394000.0,32.0,72.0,34.0,16.0,0.06,2.0,371000.0,186.0,26.0,-0.20,-0.14,0.15,0.05,38800,6,1018,729,106,87,642,673,56,123,9,4,0.10,0.12,0.88,0.92,0.08,0.33,0.70,0.25,0.14,3.13,0.17,0.01,0.01,255000.0,2020-01-01
21,1007,2021-01-01,101000.0,80500.0,0.256,0.071,0.095,-0.253,15300,0.028,14900.0,0.087,1.486,0.035,0.090,0.305,0.391,0.213,0.000,0.000,0.027,0.053,0.228,0.447,0.214,0.031,0.053,0.039,0.051,0.894,-0.022,0.914,0.003,-0.625,0.008,0.032,0.067,0.030,0.040,1.000,0.020,6240,0.057,5900.0,0.473,0.426,0.110,0.204,0.242,-0.157,0.057,0.053,0.075,953,0.443,0.447,0.557,0.553,1984.0,0.165,0.142,0.162,0.051,0.049,0.041,0.839,0.695,0.770,953.0,1,2021,2021-01-01,NaN,257000.0,337000.0,394000.0,406000.0,334000.0,NaN,304000.0,0.0894,288000.0,248000.0,-0.1390,2021-01-01,350000.0,17.0,104.0,21.0,8.0,0.24,4.0,356000.0,211.0,26.0,-0.20,0.33,-0.10,-0.02,58216,6,938,670,115,94,576,638,32,159,9,4,0.12,0.14,0.86,0.95,0.05,0.34,0.69,0.29,0.14,2.93,0.24,0.01,0.01,258000.0,2021-01-01
22,1007,2022-01-01,99500.0,86200.0,0.155,0.083,0.058,0.431,15400,0.031,14900.0,0.120,3.000,0.030,0.158,0.297,0.421,0.113,0.012,0.000,0.027,0.070,0.230,0.442,0.197,0.034,0.055,0.375,0.040,0.875,-0.062,0.933,0.011,1.750,0.004,0.032,0.067,0.030,0.046,2.538,0.013,6590,0.101,5980.0,0.450,0.447,0.007,0.197,0.225,-0.124,0.059,0.047,0.255,1000,0.423,0.446,0.577,0.554,1985.0,0.191,0.142,0.345,0.021,0.071,-0.704,0.845,0.682,0.756,1000.0,1,2022,2022-01-01,NaN,282000.0,374000.0,444000.0,454000.0,371000.0,NaN,334000.0,0.1170,288000.0,248000.0,-0.1390,2022-01-01,385000.0,10.0,52.0,13.0,8.0,0.00,0.0,389000.0,222.0,26.0,-0.40,-0.34,-0.01,0.04,77630,6,710,488,111,38,450,349,139,70,4,3,0.16,0.08,0.92,0.72,0.28,0.37,0.57,0.28,0.16,4.21,0.14,0.01,0.01,287000.0,2022-01-01

In [7]:
print(df.columns)

Index(['zcta', 'date_census', 'household_income', 'household_income_prior',
       'household_income_delta', 'pct_below_pov_line',
       'pct_below_pov_line_prior', 'pct_below_pov_line_delta', 'total_pop',
       'total_pop_delta',
       ...
       'debt_to_income', 'loan_to_value', 'pct_high_ltv', 'pct_very_high_ltv',
       'avg_first_lien_ir', 'pct_cash_out_refinance', 'pct_investor_loans',
       'pct_second_loans', 'avg_loan_amt', 'date_HMDA'],
      dtype='object', length=126)

In [8]:
na_summary = df.isna().mean().sort_values(ascending=False) * 100

In [9]:
print(df.isna().mean().sort_values(ascending=False))

all_homes_projections    1.000000
value_1_bed              0.785230
value_5_bed              0.581735
dollar_drop_2007_2012    0.309635
all_homes_200701         0.309051
                           ...
date_zillow              0.000000
date                     0.000000
active_listing_count     0.000000
total_listing_count      0.000000
date_HMDA                0.000000
Length: 126, dtype: float64

In [10]:
print(na_summary.to_string())

all_homes_projections                   100.000000
value_1_bed                              78.523032
value_5_bed                              58.173541
dollar_drop_2007_2012                    30.963536
all_homes_200701                         30.905081
value_4_bed                              28.019520
value_2_bed                              27.194948
value_3_bed                              13.127618
all_homes_201201                         11.554642
pct_asian_delta                          10.134004
pct_black_delta                           5.673696
all_homes_yy_smoothed                     2.750051
all_homes_prior                           2.664140
all_homes                                 2.080473
pct_hispanic_delta                        1.100906
pct_foreign_delta                         1.055736
median_days_on_market_yy_smoothed         0.464099
average_listing_price_yy_smoothed         0.377302
median_listing_price_yy_smoothed          0.377302
price_drops_pct_of_inventory              0.374645
total_listing_count_yy_smoothed           0.371988
pct_wfh_delta                             0.348960
f_pct_25_29                               0.258620
m_pct_25_29                               0.258620
household_income_delta                    0.219650
median_listing_price_per_square_foot      0.190422
m_pct_30_34                               0.168280
f_pct_30_34                               0.168280
median_days_on_market                     0.143481
pct_under_5_delta                         0.131967
household_income                          0.121339
household_income_prior                    0.108054
pct_vacancy_delta                         0.098311
pct_below_pov_line_delta                  0.077940
pct_under_18_delta                        0.073512
pct_wfh_prior                             0.071740
pct_below_pov_line_prior                  0.070855
pct_with_bachelor_delta                   0.067312
pct_under_5_prior                         0.066426
pct_over_65_prior                         0.066426
pct_over_65_delta                         0.066426
pct_under_18_prior                        0.066426
pct_with_bachelor_prior                   0.066426
pct_vacancy_prior                         0.066426
pct_white_prior                           0.066426
pct_foreign_prior                         0.066426
total_housing_units_delta                 0.066426
total_pop_delta                           0.066426
pct_hispanic_prior                        0.066426
total_pop_prior                           0.066426
total_housing_units_prior                 0.066426
pct_asian_prior                           0.066426
pct_white_delta                           0.066426
pct_black_prior                           0.066426
pct_2_bed_rentals                         0.064655
pct_1_bed_rentals                         0.064655
pct_0_bed_rentals                         0.064655
pct_3_bed_rentals                         0.064655
pct_5_bed_rentals                         0.064655
pct_4_bed_rentals                         0.064655
pct_second_loans                          0.045170
pct_cash_out_refinance                    0.045170
pct_investor_loans                        0.045170
pct_very_high_ltv                         0.045170
pct_high_ltv                              0.045170
pct_second_lien                           0.045170
pct_first_lien                            0.045170
pct_conv_loans                            0.045170
pct_gov_loans                             0.045170
median_listing_price                      0.023913
average_listing_price                     0.023913
pct_loan_denials                          0.008857
average_home_age                          0.007971
pct_wfh                                   0.006200
total_rental_homes                        0.004428
pct_below_pov_line                        0.004428
total_second_loans_originated             0.000000
active_listing_count_historical           0.000000
avg_loan_amt                              0.000000
total_second_property_mortgages           0.000000
total_investment_property_mortgages       0.000000
total_cash_out_refinances                 0.000000
loan_to_value                             0.000000
Unnamed: 0                                0.000000
total_first_loans_originated              0.000000
total_conv_loans_originated               0.000000
total_gov_loans_originated                0.000000
total_loans_denials                       0.000000
total_loan_origination                    0.000000
total_loan_applications                   0.000000
avg_first_lien_ir                         0.000000
X                                         0.000000
debt_to_income                            0.000000
zcta                                      0.000000
price_reduced_count                       0.000000
new_listing_count                         0.000000
total_pop                                 0.000000
pct_0_bed_stock                           0.000000
pct_1_bed_stock                           0.000000
pct_2_bed_stock                           0.000000
pct_3_bed_stock                           0.000000
pct_4_bed_stock                           0.000000
pct_5_bed_stock                           0.000000
pct_foreign                               0.000000
pct_white                                 0.000000
pct_black                                 0.000000
pct_asian                                 0.000000
pct_hispanic                              0.000000
total_housing_units                       0.000000
pct_with_bachelor                         0.000000
pct_under_18                              0.000000
pct_under_5                               0.000000
renter_occupied_homes                     0.000000
pct_over_65                               0.000000
pct_vacancy                               0.000000
date_census                               0.000000
pct_owner_occupied                        0.000000
pct_mortgage                              0.000000
pct_sfh                                   0.000000
month                                     0.000000
year                                      0.000000
date_zillow                               0.000000
date                                      0.000000
active_listing_count                      0.000000
total_listing_count                       0.000000
date_HMDA                                 0.000000

# BY INCOME

In [ ]:
cols = [
    'zcta',
    'date_census',
    'household_income',
    'household_income_prior',
    'household_income_delta',
    "median_listing_price",
    "all_homes_projections",
    "pct_below_pov_line",
    "pct_below_pov_line_prior",
    "pct_below_pov_line_delta",
    "total_pop",
    "total_pop_delta",
    "total_pop_prior",
    "pct_wfh",
    "pct_wfh_delta",
    "pct_wfh_prior",


]

df_income = df[cols].copy()

# BY Demographic

In [64]:
cols = [
'zcta',
'date_census',
"all_homes",
"all_homes_projections",
"all_homes_prior",
"all_homes_yy_smoothed",
"pct_foreign",
"pct_foreign_delta",
"pct_foreign_prior",
"pct_white",
"pct_white_delta",
"pct_white_prior",
"pct_black",
"pct_black_delta",
"pct_black_prior",
"pct_asian",
"pct_asian_delta",
"pct_asian_prior",
"pct_hispanic",
"pct_hispanic_delta",
"pct_hispanic_prior", 
"pct_with_bachelor"	,
"pct_with_bachelor_prior",
"pct_with_bachelor_delta",
"pct_under_18",
"pct_under_18_prior",
"pct_under_18_delta",
"pct_under_5",
"pct_under_5_prior",
"pct_under_5_delta",
"pct_over_65",
"pct_over_65_prior",
"pct_over_65_delta"




]
df_demo = df[cols].copy()

# By Supply

In [62]:
cols = [
'zcta',
'date_census',
"all_homes",
"all_homes_projections",
"all_homes_prior",
"all_homes_yy_smoothed",
"total_housing_units",
"total_housing_units_delta",
"total_housing_units_prior",
"average_home_age",
"pct_vacancy",
"pct_vacancy_prior",
"pct_vacancy_delta",
"pct_owner_occupied",
"pct_mortgage",
"median_listing_price",
"active_listing_count",
"median_days_on_market",
"total_listing_count",
"new_listing_count",
"price_drops_pct_of_inventory",
"price_reduced_count",
"average_listing_price",
"median_listing_price_per_square_foot",
"active_listing_count_historical",
"total_listing_count_yy_smoothed",
"median_days_on_market_yy_smoothed",
"median_listing_price_yy_smoothed",
"average_listing_price_yy_smoothed"

]


df_supply = df[cols].copy()

#### BY INCOME 
This is the thing I did before meeting 2/10

In [34]:
cols = [
    'zcta',
    'date_census',
    'household_income',
    'household_income_prior',
    'household_income_delta',
    "median_listing_price",
    "all_homes_projections"
]

df_income = df[cols].copy()

In [39]:
df_income['median_listing_price'].isna().mean()
# 0.023913

np.float64(0.0002391348632060014)

In [35]:
df_income.duplicated(['zcta', 'date_census']).sum()

np.int64(0)

In [36]:
df_income['date_census'].dtype

dtype('O')

In [41]:
import pandas as pd

df_income['date_census'] = pd.to_datetime(
    df_income['date_census'],
    format='%Y-%m-%d',
    errors='coerce'
)
df_income['date_census'].dtype

dtype('<M8[ns]')

In [42]:
df_income.head(15)

,zcta,date_census,household_income,household_income_prior,household_income_delta,median_listing_price,all_homes_projections
0,1001,2018-01-01,62100.0,58700.0,0.058,222000.0,NaN
1,1001,2019-01-01,63900.0,60800.0,0.052,206000.0,NaN
2,1001,2020-01-01,66100.0,60200.0,0.099,252000.0,NaN
3,1001,2021-01-01,72400.0,56700.0,0.277,249000.0,NaN
4,1001,2022-01-01,73400.0,57700.0,0.272,232000.0,NaN
5,1001,2023-01-01,71900.0,62100.0,0.157,357000.0,NaN
6,1002,2018-01-01,55900.0,54400.0,0.026,367000.0,NaN
7,1002,2019-01-01,61200.0,55100.0,0.110,490000.0,NaN
8,1002,2020-01-01,60500.0,50500.0,0.198,456000.0,NaN
9,1002,2021-01-01,65000.0,48900.0,0.329,549000.0,NaN
10,1002,2022-01-01,74300.0,52400.0,0.418,535000.0,NaN
11,1002,2023-01-01,69400.0,55900.0,0.243,535000.0,NaN
12,1005,2018-01-01,68300.0,68600.0,-0.005,254000.0,NaN
13,1005,2019-01-01,67300.0,68400.0,-0.015,242000.0,NaN
14,1005,2020-01-01,80100.0,68800.0,0.164,287000.0,NaN

In [43]:
df_income = df_income.sort_values(['zcta', 'date_census']).copy()

In [45]:
df_income['year'] = df_income['date_census'].dt.year

In [47]:
df_income['target_mlp_1y'] = (
    df_income
    .groupby('zcta')['median_listing_price']
    .shift(-1)
)

In [48]:
df_income['mlp_lag1'] = (
    df_income
    .groupby('zcta')['median_listing_price']
    .shift(1)
)

df_income['mlp_lag2'] = (
    df_income
    .groupby('zcta')['median_listing_price']
    .shift(2)
)

In [49]:
df_model = df_income.dropna(
    subset=[
        'median_listing_price',
        'target_mlp_1y',
        'mlp_lag1'
    ]
).copy()

In [50]:
df_model.head(15)

,zcta,date_census,household_income,household_income_prior,household_income_delta,median_listing_price,all_homes_projections,year,mlp_lag1,mlp_lag2,target_mlp_1y
1,1001,2019-01-01,63900.0,60800.0,0.052,206000.0,NaN,2019,222000.0,NaN,252000.0
2,1001,2020-01-01,66100.0,60200.0,0.099,252000.0,NaN,2020,206000.0,222000.0,249000.0
3,1001,2021-01-01,72400.0,56700.0,0.277,249000.0,NaN,2021,252000.0,206000.0,232000.0
4,1001,2022-01-01,73400.0,57700.0,0.272,232000.0,NaN,2022,249000.0,252000.0,357000.0
7,1002,2019-01-01,61200.0,55100.0,0.110,490000.0,NaN,2019,367000.0,NaN,456000.0
8,1002,2020-01-01,60500.0,50500.0,0.198,456000.0,NaN,2020,490000.0,367000.0,549000.0
9,1002,2021-01-01,65000.0,48900.0,0.329,549000.0,NaN,2021,456000.0,490000.0,535000.0
10,1002,2022-01-01,74300.0,52400.0,0.418,535000.0,NaN,2022,549000.0,456000.0,535000.0
13,1005,2019-01-01,67300.0,68400.0,-0.015,242000.0,NaN,2019,254000.0,NaN,287000.0
14,1005,2020-01-01,80100.0,68800.0,0.164,287000.0,NaN,2020,242000.0,254000.0,375000.0
15,1005,2021-01-01,103000.0,70600.0,0.466,375000.0,NaN,2021,287000.0,242000.0,590000.0
16,1005,2022-01-01,97400.0,70300.0,0.385,590000.0,NaN,2022,375000.0,287000.0,152000.0
19,1007,2019-01-01,91200.0,74200.0,0.229,315000.0,NaN,2019,376000.0,NaN,394000.0
20,1007,2020-01-01,94800.0,76900.0,0.233,394000.0,NaN,2020,315000.0,376000.0,350000.0
21,1007,2021-01-01,101000.0,80500.0,0.256,350000.0,NaN,2021,394000.0,315000.0,385000.0

In [51]:
train_df = df_model[df_model['year'] <= 2021].copy()
val_df   = df_model[df_model['year'] == 2022].copy()

pred_2024_df = df_income[df_income['year'] == 2023].copy()

In [52]:
features = [
    'zcta',
    'year',
    'median_listing_price',
    'mlp_lag1',
    'household_income',
    'household_income_prior',
    'household_income_delta'
]

target = 'target_mlp_1y'

In [53]:
from catboost import CatBoostRegressor

In [54]:
cat_features = ['zcta']

model = CatBoostRegressor(
    iterations=800,
    learning_rate=0.05,
    depth=8,
    loss_function='RMSE',
    random_seed=42,
    verbose=100
)

model.fit(
    train_df[features],
    train_df[target],
    cat_features=cat_features,
    eval_set=(val_df[features], val_df[target]),
    use_best_model=True
)

0:	learn: 472341.4293830	test: 461832.1807850	best: 461832.1807850 (0)	total: 76.8ms	remaining: 1m 1s
100:	learn: 240659.5307029	test: 317576.1853247	best: 259884.3742416 (31)	total: 1.64s	remaining: 11.4s
200:	learn: 212702.1514475	test: 341293.7601102	best: 259884.3742416 (31)	total: 2.78s	remaining: 8.27s
300:	learn: 194365.6687517	test: 363149.6874669	best: 259884.3742416 (31)	total: 3.83s	remaining: 6.36s
400:	learn: 181395.6229312	test: 376657.5050071	best: 259884.3742416 (31)	total: 4.76s	remaining: 4.74s
500:	learn: 171092.6960141	test: 387156.8746968	best: 259884.3742416 (31)	total: 5.59s	remaining: 3.34s
600:	learn: 159855.6219982	test: 390427.1890503	best: 259884.3742416 (31)	total: 6.72s	remaining: 2.23s
700:	learn: 151947.9196274	test: 392606.3582479	best: 259884.3742416 (31)	total: 7.83s	remaining: 1.1s
799:	learn: 145357.7410208	test: 393741.3683190	best: 259884.3742416 (31)	total: 8.98s	remaining: 0us

bestTest = 259884.3742
bestIteration = 31

Shrink model to first 32 iterations.

In [55]:
from sklearn.metrics import mean_absolute_percentage_error, mean_squared_error
import numpy as np

val_preds = model.predict(val_df[features])

rmse = np.sqrt(mean_squared_error(val_df[target], val_preds))
mape = mean_absolute_percentage_error(val_df[target], val_preds)

print("Validation RMSE:", rmse)
print("Validation MAPE:", mape)

Validation RMSE: 259884.3742416131
Validation MAPE: 5.411538397670424e+16

In [56]:
pred_2024_df['all_homes_projections'] = model.predict(
    pred_2024_df[features]
)